modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"
[[mods]]
modId="eternalhearts"
version="1.0.0"
displayName="Eternal Hearts"
logoFile="logo.png"
credits="Created with love"
authors="EternalHearts Team"
description='''A Minecraft mod adding bronze, steel, voidite, and eternal hearts!'''
[[dependencies.eternalhearts]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.eternalhearts]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"
